name: Journey Library CI Pipeline

on:
  push:
    branches:
      - '**' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # generate README.md for journey files
  readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install frodo-cli
        run: |
          npm i -g @rockcarver/frodo-cli
          frodo -v

      - name: Generate README.md files
        run: |
          find . -name "*.journey.json" -exec sh -c 'frodo journey describe -f "$0" --markdown --output-file "${0%/*}/README.md"' {} \;
        
      - name: Show changes
        run: |
          git status
        
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Added or updated Reamdme files"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          labels: automated-pr
          team-reviewers: |
            owners
            maintainers
          
